// <auto-generated />
using System;
using Maliev.JobService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.JobService.Infrastructure.Migrations
{
    [DbContext(typeof(JobDbContext))]
    [Migration("20260404000000_AddSchedulingIndexes")]
    partial class AddSchedulingIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.JobService.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedMachineId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_machine_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EstimatedPrintTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_print_time_minutes");

                    b.Property<bool>("IsOutsourced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_outsourced");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("integer")
                        .HasColumnName("queue_position");

                    b.Property<DateTime?>("ScheduledEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end_time");

                    b.Property<DateTime?>("ScheduledStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start_time");

                    b.Property<int>("SetupTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("setup_time_minutes");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("technology");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("VolumeCm3")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("volume_cm3");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMachineId")
                        .HasDatabaseName("ix_jobs_assigned_machine_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_jobs_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_jobs_status");

                    b.HasIndex("AssignedMachineId", "QueuePosition")
                        .HasDatabaseName("ix_jobs_machine_queue_position");

                    b.HasIndex("AssignedMachineId", "ScheduledStartTime")
                        .HasDatabaseName("ix_jobs_machine_scheduled_start");

                    b.ToTable("jobs", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
